/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PresentRouteImport } from './routes/present'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as JoinTeamRouteImport } from './routes/join-team'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as CreateTeamRouteImport } from './routes/create-team'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhysioIndexRouteImport } from './routes/physio.index'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as AthleteIndexRouteImport } from './routes/athlete.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PhysioLogRouteImport } from './routes/physio.log'
import { Route as CoachProgramRouteImport } from './routes/coach.program'
import { Route as AthleteWorkoutRouteImport } from './routes/athlete.workout'
import { Route as AthleteProgressRouteImport } from './routes/athlete.progress'
import { Route as AthleteInjuryRouteImport } from './routes/athlete.injury'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentRoute = PresentRouteImport.update({
  id: '/present',
  path: '/present',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTeamRoute = JoinTeamRouteImport.update({
  id: '/join-team',
  path: '/join-team',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTeamRoute = CreateTeamRouteImport.update({
  id: '/create-team',
  path: '/create-team',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysioIndexRoute = PhysioIndexRouteImport.update({
  id: '/physio/',
  path: '/physio/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteIndexRoute = AthleteIndexRouteImport.update({
  id: '/athlete/',
  path: '/athlete/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysioLogRoute = PhysioLogRouteImport.update({
  id: '/physio/log',
  path: '/physio/log',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachProgramRoute = CoachProgramRouteImport.update({
  id: '/coach/program',
  path: '/coach/program',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteWorkoutRoute = AthleteWorkoutRouteImport.update({
  id: '/athlete/workout',
  path: '/athlete/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteProgressRoute = AthleteProgressRouteImport.update({
  id: '/athlete/progress',
  path: '/athlete/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteInjuryRoute = AthleteInjuryRouteImport.update({
  id: '/athlete/injury',
  path: '/athlete/injury',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/create-team': typeof CreateTeamRoute
  '/feed': typeof FeedRoute
  '/join-team': typeof JoinTeamRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/present': typeof PresentRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/athlete/injury': typeof AthleteInjuryRoute
  '/athlete/progress': typeof AthleteProgressRoute
  '/athlete/workout': typeof AthleteWorkoutRoute
  '/coach/program': typeof CoachProgramRoute
  '/physio/log': typeof PhysioLogRoute
  '/admin/': typeof AdminIndexRoute
  '/athlete/': typeof AthleteIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/physio/': typeof PhysioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/create-team': typeof CreateTeamRoute
  '/feed': typeof FeedRoute
  '/join-team': typeof JoinTeamRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/present': typeof PresentRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/athlete/injury': typeof AthleteInjuryRoute
  '/athlete/progress': typeof AthleteProgressRoute
  '/athlete/workout': typeof AthleteWorkoutRoute
  '/coach/program': typeof CoachProgramRoute
  '/physio/log': typeof PhysioLogRoute
  '/admin': typeof AdminIndexRoute
  '/athlete': typeof AthleteIndexRoute
  '/coach': typeof CoachIndexRoute
  '/physio': typeof PhysioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/create-team': typeof CreateTeamRoute
  '/feed': typeof FeedRoute
  '/join-team': typeof JoinTeamRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/present': typeof PresentRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/athlete/injury': typeof AthleteInjuryRoute
  '/athlete/progress': typeof AthleteProgressRoute
  '/athlete/workout': typeof AthleteWorkoutRoute
  '/coach/program': typeof CoachProgramRoute
  '/physio/log': typeof PhysioLogRoute
  '/admin/': typeof AdminIndexRoute
  '/athlete/': typeof AthleteIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/physio/': typeof PhysioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/create-team'
    | '/feed'
    | '/join-team'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/present'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/athlete/injury'
    | '/athlete/progress'
    | '/athlete/workout'
    | '/coach/program'
    | '/physio/log'
    | '/admin/'
    | '/athlete/'
    | '/coach/'
    | '/physio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/create-team'
    | '/feed'
    | '/join-team'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/present'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/athlete/injury'
    | '/athlete/progress'
    | '/athlete/workout'
    | '/coach/program'
    | '/physio/log'
    | '/admin'
    | '/athlete'
    | '/coach'
    | '/physio'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/create-team'
    | '/feed'
    | '/join-team'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/present'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/athlete/injury'
    | '/athlete/progress'
    | '/athlete/workout'
    | '/coach/program'
    | '/physio/log'
    | '/admin/'
    | '/athlete/'
    | '/coach/'
    | '/physio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CreateTeamRoute: typeof CreateTeamRoute
  FeedRoute: typeof FeedRoute
  JoinTeamRoute: typeof JoinTeamRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PresentRoute: typeof PresentRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AthleteInjuryRoute: typeof AthleteInjuryRoute
  AthleteProgressRoute: typeof AthleteProgressRoute
  AthleteWorkoutRoute: typeof AthleteWorkoutRoute
  CoachProgramRoute: typeof CoachProgramRoute
  PhysioLogRoute: typeof PhysioLogRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AthleteIndexRoute: typeof AthleteIndexRoute
  CoachIndexRoute: typeof CoachIndexRoute
  PhysioIndexRoute: typeof PhysioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present': {
      id: '/present'
      path: '/present'
      fullPath: '/present'
      preLoaderRoute: typeof PresentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-team': {
      id: '/join-team'
      path: '/join-team'
      fullPath: '/join-team'
      preLoaderRoute: typeof JoinTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-team': {
      id: '/create-team'
      path: '/create-team'
      fullPath: '/create-team'
      preLoaderRoute: typeof CreateTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physio/': {
      id: '/physio/'
      path: '/physio'
      fullPath: '/physio/'
      preLoaderRoute: typeof PhysioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/': {
      id: '/athlete/'
      path: '/athlete'
      fullPath: '/athlete/'
      preLoaderRoute: typeof AthleteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physio/log': {
      id: '/physio/log'
      path: '/physio/log'
      fullPath: '/physio/log'
      preLoaderRoute: typeof PhysioLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/program': {
      id: '/coach/program'
      path: '/coach/program'
      fullPath: '/coach/program'
      preLoaderRoute: typeof CoachProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/workout': {
      id: '/athlete/workout'
      path: '/athlete/workout'
      fullPath: '/athlete/workout'
      preLoaderRoute: typeof AthleteWorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/progress': {
      id: '/athlete/progress'
      path: '/athlete/progress'
      fullPath: '/athlete/progress'
      preLoaderRoute: typeof AthleteProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/injury': {
      id: '/athlete/injury'
      path: '/athlete/injury'
      fullPath: '/athlete/injury'
      preLoaderRoute: typeof AthleteInjuryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CreateTeamRoute: CreateTeamRoute,
  FeedRoute: FeedRoute,
  JoinTeamRoute: JoinTeamRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PresentRoute: PresentRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AthleteInjuryRoute: AthleteInjuryRoute,
  AthleteProgressRoute: AthleteProgressRoute,
  AthleteWorkoutRoute: AthleteWorkoutRoute,
  CoachProgramRoute: CoachProgramRoute,
  PhysioLogRoute: PhysioLogRoute,
  AdminIndexRoute: AdminIndexRoute,
  AthleteIndexRoute: AthleteIndexRoute,
  CoachIndexRoute: CoachIndexRoute,
  PhysioIndexRoute: PhysioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
